const NOTES = [
  { day: 1, title: "Linux DAY-1", description: "Kali Linux — Beginner Notes.", file: "Kali_Linux_Beginner_Notes_Day1.pdf" },
  { day: 2, title: "DAY-2 — Networking Basics", description: "Understand IP addresses, ports, protocols, and how devices communicate.", file: "Day-02-Networking-Basics.pdf" },
  { day: 3, title: "DAY-3 — Linux Command Line", description: "Build confidence with everyday terminal commands and navigation.", file: "Day-03-Linux-Command-Line.pdf" },
  { day: 4, title: "DAY-4 — Linux Permissions", description: "Learn read, write, and execute permissions and why they matter for security.", file: "Day-04-Linux-Permissions.pdf" },
  { day: 5, title: "DAY-5 — Processes & Services", description: "Understand running programs, processes, and services in Linux.", file: "Day-05-Processes-Services.pdf" },
  { day: 6, title: "DAY-6 — Users, Groups & sudo", description: "Learn basic Linux account management and privilege boundaries.", file: "Day-06-Users-Groups-sudo.pdf" },
  { day: 7, title: "DAY-7 — Bash Scripting Basics", description: "Automate simple repetitive tasks with shell scripts.", file: "Day-07-Bash-Scripting-Basics.pdf" },
  { day: 8, title: "DAY-8 — Networking Troubleshooting", description: "Use basic tools to understand connectivity problems.", file: "Day-08-Networking-Troubleshooting.pdf" },
  { day: 9, title: "DAY-9 — DNS Basics", description: "Understand how names are translated into IP addresses.", file: "Day-09-DNS-Basics.pdf" },
  { day: 10, title: "DAY-10 — HTTP & HTTPS", description: "Understand the basics of web requests and responses.", file: "Day-10-HTTP-HTTPS.pdf" },
  { day: 11, title: "DAY-11 — Nmap Fundamentals", description: "Learn the purpose of Nmap for authorized network discovery.", file: "Day-11-Nmap-Fundamentals.pdf" },
  { day: 12, title: "DAY-12 — Wireshark Fundamentals", description: "Learn to observe network traffic in a controlled environment.", file: "Day-12-Wireshark-Fundamentals.pdf" },
  { day: 13, title: "DAY-13 — Burp Suite Basics", description: "Learn web request/response analysis using an authorized lab.", file: "Day-13-Burp-Suite-Basics.pdf" },
  { day: 14, title: "DAY-14 — Web Security Concepts", description: "Build a foundation in common web security risks.", file: "Day-14-Web-Security-Concepts.pdf" },
  { day: 15, title: "DAY-15 — SQL Fundamentals", description: "Understand relational databases and basic SQL syntax.", file: "Day-15-SQL-Fundamentals.pdf" },
  { day: 16, title: "DAY-16 — SQL Injection Concepts", description: "Understand the idea of SQL injection without targeting real systems.", file: "Day-16-SQL-Injection-Concepts.pdf" },
  { day: 17, title: "DAY-17 — Authentication & Password Security", description: "Learn how secure authentication is designed.", file: "Day-17-Authentication-Password-Security.pdf" },
  { day: 18, title: "DAY-18 — Cryptography Basics", description: "Understand encryption, hashing, encoding, and digital signatures.", file: "Day-18-Cryptography-Basics.pdf" },
  { day: 19, title: "DAY-19 — Logs & Monitoring", description: "Learn why logs are important for security and troubleshooting.", file: "Day-19-Logs-Monitoring.pdf" },
  { day: 20, title: "DAY-20 — Basic Security Hardening", description: "Reduce unnecessary attack surface on a Linux system.", file: "Day-20-Basic-Security-Hardening.pdf" },
  { day: 21, title: "DAY-21 — Firewalls & Ports", description: "Understand how host firewalls control network connections.", file: "Day-21-Firewalls-Ports.pdf" },
  { day: 22, title: "DAY-22 — Vulnerability Management", description: "Learn a practical defensive workflow for handling vulnerabilities.", file: "Day-22-Vulnerability-Management.pdf" },
  { day: 23, title: "DAY-23 — CTF & Cybersecurity Labs", description: "Learn how to use legal practice environments effectively.", file: "Day-23-CTF-Cybersecurity-Labs.pdf" },
  { day: 24, title: "DAY-24 — Web Enumeration Concepts", description: "Understand asset and content discovery in authorized web labs.", file: "Day-24-Web-Enumeration-Concepts.pdf" },
  { day: 25, title: "DAY-25 — curl & Web Testing", description: "Use curl to understand HTTP from the command line.", file: "Day-25-curl-Web-Testing.pdf" },
  { day: 26, title: "DAY-26 — Git & GitHub Basics", description: "Learn version control for cybersecurity notes and projects.", file: "Day-26-Git-GitHub-Basics.pdf" },
  { day: 27, title: "DAY-27 — Security Documentation", description: "Turn technical work into clear, reproducible notes.", file: "Day-27-Security-Documentation.pdf" },
  { day: 28, title: "DAY-28 — Incident Response Basics", description: "Understand the basic lifecycle of responding to a security incident.", file: "Day-28-Incident-Response-Basics.pdf" },
  { day: 29, title: "DAY-29 — Cybersecurity Career Roadmap", description: "Map beginner skills into practical learning tracks.", file: "Day-29-Cybersecurity-Career-Roadmap.pdf" },
  { day: 30, title: "DAY-30 — 30-Day Cybersecurity Revision", description: "Review the first 30 days and create a repeatable learning system.", file: "Day-30-30-Day-Cybersecurity-Revision.pdf" }
];